config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "mains#index"
  resources :posts
  resources :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

    has_many :comments
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def new
        @comment = Comment.new
    end

    def create
        @comment = Comment.new(comment_params)
        if @comment.save
            redirect_to new_post_path, notice: "comment"
        else
            render :new
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:comment, :user_id, :post_id )
    end
end

app/controllers/mains_controller.rb
class MainsController <ApplicationController

    def index
        
    end

    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def new
        @post = Post.new
    end

    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
        @comment = @post.comments.build
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path, notice: "post successfully"
        else
            render :new
        end
    end

    private
    def post_params
        params.require(:post).permit(:tital, :post_field, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
 <h3> Comment </h3>

   <%= simple_form_for @comment, data:{turbo: false} do |f| %>
   <%= f.hidden_field :user_id, value:  current_user.id %>
   <%= f.hidden_field(:post_id, value:  @post.id) %>
 
    <div class= "mt-4">
      <%= f.input :comment %>  
    </div> 
    <div class= "mt-4 ">
      <%= f.submit "comment" , class: "btn btn-primary"%>
    </div>
   <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewDevise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
   
  <body>
    <%= render partial: "devise/shared/navbar" %>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
  </body>
</html>

app/views/mains/index.html.erb
<h1> wellcom to my app </h1>

app/views/posts/index.html.erb
<h1> Post Index </h1>

<table class= "table">
  
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tital</th>
      <th scope="col">post_field</th>
      <th scope="col"></th>

    </tr>
  </thead>
  <tbody>
     <%@posts.each do |post| %>
      <tr>
        <td><%= post.id%></td>
        <td><%= post.tital%></td>
        <td><%= post.post_field%></td>
        <td><%= link_to "show data", post_path(post.id), class: "btn btn-primary"%></td>
    
      </tr>
    <%end%>
    
  </tbody>
     
</table>

app/views/posts/new.html.erb
<h2> My post </h2>

<%= simple_form_for @post do |f| %>
 <%= f.hidden_field :user_id, value:   current_user.id %>
    <div class="card " style="background-color:#dee2e6; ">
        <div class="card-body">
            <div class= "mt-1">
             <%= f.input :tital %>
              </div>
                <div class= "mt-4">
                <%= f.input :post_field %>
                </div>
              <div class= "mt-4">
             <%= f.submit "post" , class:"btn btn-primary" %>
            </div>
        </div>
    </div>
 
<% end %>   

app/views/posts/show.html.erb
<h2> Show posts </h2>

  <strong> Tital: </strong>
   <%= @post.tital %>
  <br>
  <strong> Post_field </strong>
   <%= @post.post_field %>

   <h3> Comment </h3>

<%= simple_form_for @comment, data:{turbo: false} do |f| %>

 <%= f.hidden_field :user_id, value:  current_user.id %>
 <%= f.hidden_field(:post_id, value:  @post.id) %>
 
          <div class= "mt-1">
             <%= f.input :text %>
              </div>
              <div class= "mt-4">
             <%= f.submit "comment" , class:"btn btn-primary" %>
          </div>
 
<% end %>   